spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user
    username: root
    password:
  jpa:
                    show-sql: false
  hibernate:
      ddl-auto: validate

      ddl-auto=none:properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        format_sql: true

